/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import static jframe.DBConnection.con;


/**
 * Add book to library
 */
public class AddBook extends javax.swing.JFrame {

    // book infomation to add
    String productName,unitBuyPrice,unitSellPrice,subCategoryId, categoryId;
    
    
    public AddBook() {
        initComponents();
        getAllCategories();
    }
    
    
     /**
     * Add book information to library
     */
    public boolean addBook() {
        // Check add failed
        boolean isAdded = false;
        
        // Get information to add 
        productName = txt_productName.getText();
        unitBuyPrice=txt_unitBuyPrice.getText();
        unitSellPrice=txt_unitSellPrice.getText();
        System.out.println("check"+productName+unitBuyPrice+unitSellPrice);
        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from categories where name = "+ "'"+ categoryComboBox.getSelectedItem()+"';";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
            categoryId=rs.getString("id");
            }
            //inset product
            String sql1 = "insert into products (name, categoryId) values"
                    + "(?,?)";
            
            PreparedStatement pst1 = con.prepareStatement(sql1);
            pst1.setString(1, productName);
            pst1.setString(2, categoryId);
            int rowCount = pst1.executeUpdate();

            //lay productId de insert productStock
            String sql2 = "select * from products where name = "+ "'"+ productName+"';";
           PreparedStatement pst2 = con.prepareStatement(sql2);
            String productId="";
            ResultSet rs2 = pst2.executeQuery(sql2);
            while(rs2.next()){
            productId=rs2.getString("id");
            }
            
            //insert productStock
            String sql3 = "insert into productStocks (productId,unitBuyPrice,unitSellPrice) values (?,?,?)";
                        PreparedStatement pst3 = con.prepareStatement(sql3);

            pst3.setString(1, productId);
            pst3.setString(2, unitBuyPrice);
            pst3.setString(3, unitSellPrice);
                        int rowCount1 = pst3.executeUpdate();

            
            if(rowCount > 0&&rowCount1>0) {
                isAdded = true;
            }
            else {
                isAdded = false;
            } 
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isAdded;

    }
    
   public ArrayList getAllCategories(){
                    ArrayList<String> categoryList = new ArrayList<String>();

       try{
            Connection con = DBConnection.getConnection();
            String sql="SELECT * FROM categories;";
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            categoryComboBox.removeAllItems();
            while(rs.next()){
                String category = rs.getString("name");
                categoryComboBox.addItem(category);
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
       return categoryList;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();
        jLabel13 = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_unitBuyPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_productName = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txt_unitSellPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unit Buy Price");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 40));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 60, 40));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonCircle4.setText("Add product");
        rSMaterialButtonCircle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle4MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 380, 60));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 180, 40));

        notification.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        notification.setForeground(new java.awt.Color(0, 102, 153));
        notification.setText("Cập nhật thành công");
        jPanel1.add(notification, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 230, 36));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 30, 40));

        jLabel1.setText("Add product");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 60));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 60, 40));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, 40));

        txt_unitBuyPrice.setBackground(new java.awt.Color(0, 102, 153));
        txt_unitBuyPrice.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        txt_unitBuyPrice.setForeground(new java.awt.Color(153, 153, 153));
        txt_unitBuyPrice.setText("enter buy price ...");
        txt_unitBuyPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_unitBuyPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_unitBuyPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_unitBuyPriceFocusLost(evt);
            }
        });
        txt_unitBuyPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitBuyPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_unitBuyPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 310, 40));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Unit Sell Price");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 180, 40));

        txt_productName.setBackground(new java.awt.Color(0, 102, 153));
        txt_productName.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        txt_productName.setForeground(new java.awt.Color(153, 153, 153));
        txt_productName.setText("Nhập tên sách ...");
        txt_productName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_productName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_productNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_productNameFocusLost(evt);
            }
        });
        txt_productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productNameActionPerformed(evt);
            }
        });
        txt_productName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_productNamePropertyChange(evt);
            }
        });
        txt_productName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_productNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_productNameKeyTyped(evt);
            }
        });
        txt_productName.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txt_productNameVetoableChange(evt);
            }
        });
        jPanel1.add(txt_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 310, 40));

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 330, 40));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Category");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 40));

        txt_unitSellPrice.setBackground(new java.awt.Color(0, 102, 153));
        txt_unitSellPrice.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        txt_unitSellPrice.setForeground(new java.awt.Color(153, 153, 153));
        txt_unitSellPrice.setText("enter sell price ...");
        txt_unitSellPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_unitSellPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_unitSellPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_unitSellPriceFocusLost(evt);
            }
        });
        txt_unitSellPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitSellPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_unitSellPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 310, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        setSize(new java.awt.Dimension(990, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        System.out.println("actionPerformed"+productName+unitBuyPrice+unitSellPrice);

        if(this.addBook()== true){
            notification.setText("Cập nhật thành công");
            this.notification.setForeground(Color.yellow);
        }
        else {
            notification.setText("Cập nhật thất bại");
            this.notification.setForeground(Color.yellow);
        }
        
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        System.out.println("clicked"+productName+unitBuyPrice+unitSellPrice);
        
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_unitBuyPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unitBuyPriceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitBuyPriceFocusGained

    private void txt_unitBuyPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unitBuyPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitBuyPriceFocusLost

    private void txt_unitBuyPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitBuyPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitBuyPriceActionPerformed

    private void txt_productNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_productNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameFocusGained

    private void txt_productNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_productNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameFocusLost

    private void txt_productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameActionPerformed

    private void txt_productNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_productNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNamePropertyChange

    private void txt_productNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameKeyReleased

    private void txt_productNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameKeyTyped

    private void txt_productNameVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txt_productNameVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productNameVetoableChange

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("selected"+categoryComboBox.getSelectedItem());
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void txt_unitSellPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unitSellPriceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitSellPriceFocusGained

    private void txt_unitSellPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unitSellPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitSellPriceFocusLost

    private void txt_unitSellPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitSellPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitSellPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel notification;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private javax.swing.JTextField txt_productName;
    private javax.swing.JTextField txt_unitBuyPrice;
    private javax.swing.JTextField txt_unitSellPrice;
    // End of variables declaration//GEN-END:variables
}
