/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;


import java.sql.Connection;
import java.sql.*;
import java.awt.Color;
import java.awt.Component;
import java.util.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import swing.DataSearch;
import swing.EventClick;
import swing.PanelSearch;
/**
 *
 * Panel to borrow book
 */
public class Onlymovie extends javax.swing.JPanel {
    
        DefaultTableModel model;
    //Contructor
    public Onlymovie() {
        initComponents();
        this.setMovieToTable();

    }
    public void setMovieToTable( ){
        try{
            Connection con = DBConnection.getConnection();
            String sql="select m.id as id,p.name as name, m.director as director,m.actor as actor,sc.name as subCategoryName,ps.unitBuyPrice as unitBuyPrice,ps.unitSellPrice as unitSellPrice,ps.totalBuyPrice as totalBuyPrice,ps.totalSellPrice as totalSellPrice, ps.totalStock as totalStock from movieinfor as m left join products as p on (p.id = m.productId) left join subCategories as sc on (sc.id=p.subCategoryId) left join productStocks as ps on (ps.productId=p.id);";
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("id") ;
                String name = rs.getString("name");
                String director = rs.getString("director");
                String actor = rs.getString("actor");
                String subCategoryName = rs.getString("subCategoryName");
                String totalStock=rs.getString("totalStock");
                String unitBuyPrice=rs.getString("unitBuyPrice");
                String unitSellPrice=rs.getString("unitSellPrice");
                String totalBuyPrice=rs.getString("totalBuyPrice");
                String totalSellPrice=rs.getString("totalSellPrice");
                Object obj[] = {id, name, director, actor, subCategoryName,unitBuyPrice,unitSellPrice,totalBuyPrice,totalSellPrice,totalStock};
                model = (DefaultTableModel) productTable.getModel();
                model.addRow(obj);
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new rojeru_san.complementos.RSTableMetro();

        setBackground(new java.awt.Color(102, 102, 102));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(1200, 770));
        setPreferredSize(new java.awt.Dimension(1308, 811));

        book.setBackground(new java.awt.Color(51, 51, 51));
        book.setPreferredSize(new java.awt.Dimension(1308, 811));
        book.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(59, 60, 63));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Sửa sản phẩm");
        jPanel21.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, -1));

        book.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 230, 70));

        txt_bookName.setBackground(new java.awt.Color(51, 51, 51));
        txt_bookName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_bookName.setForeground(new java.awt.Color(153, 153, 153));
        txt_bookName.setText("Nhập tên sách, tác giả hoặc thể loại ...");
        txt_bookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bookNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookNameFocusLost(evt);
            }
        });
        txt_bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookNameActionPerformed(evt);
            }
        });
        txt_bookName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_bookNamePropertyChange(evt);
            }
        });
        txt_bookName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bookNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bookNameKeyTyped(evt);
            }
        });
        txt_bookName.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txt_bookNameVetoableChange(evt);
            }
        });
        book.add(txt_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 400, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tìm kiếm sản phẩm");
        book.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 40));

        jLabel29.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        book.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 60, 40));

        jPanel23.setBackground(new java.awt.Color(59, 60, 63));
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Thêm sản phẩm");
        jPanel23.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 24, 250, 30));

        book.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 350, 70));

        productTable.setBackground(new java.awt.Color(204, 204, 204));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "director", "actor", "subCategoryName", "unitBuyPrice", "unitSellPrice", "totalBuyPrice", "totalSellPrice", "totalStock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        productTable.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        productTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        productTable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        productTable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        productTable.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        productTable.setColorSelForeground(new java.awt.Color(0, 0, 0));
        productTable.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        productTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable.setFuenteHead(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        productTable.setRowHeight(40);
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        book.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1200, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBookSearchMouseClicked
   
    }//GEN-LAST:event_txtBookSearchMouseClicked

    private void txtBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookSearchActionPerformed

    private void txtBookSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookSearchKeyReleased
   
    }//GEN-LAST:event_txtBookSearchKeyReleased

    private void txtStudentSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentSearchMouseClicked
    
    }//GEN-LAST:event_txtStudentSearchMouseClicked

    private void txtStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentSearchActionPerformed

    private void txtStudentSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentSearchKeyReleased
   
    }//GEN-LAST:event_txtStudentSearchKeyReleased

    private void txtBookSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookSearchFocusGained
      
    }//GEN-LAST:event_txtBookSearchFocusGained

    private void txtBookSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookSearchFocusLost

    }//GEN-LAST:event_txtBookSearchFocusLost

    private void txtStudentSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentSearchFocusGained
      
    }//GEN-LAST:event_txtStudentSearchFocusGained

    private void txtStudentSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentSearchFocusLost
 
    }//GEN-LAST:event_txtStudentSearchFocusLost

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
      

    }//GEN-LAST:event_jPanel21MouseClicked

    private void txt_bookNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookNameFocusGained
        
    }//GEN-LAST:event_txt_bookNameFocusGained

    private void txt_bookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookNameFocusLost
        
    }//GEN-LAST:event_txt_bookNameFocusLost

    private void txt_bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookNameActionPerformed

    private void txt_bookNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_bookNamePropertyChange
        //        this.txt_bookId.setText(this.txt_bookName.getText());
    }//GEN-LAST:event_txt_bookNamePropertyChange

    private void txt_bookNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bookNameKeyReleased
        
    }//GEN-LAST:event_txt_bookNameKeyReleased

    private void txt_bookNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bookNameKeyTyped

    }//GEN-LAST:event_txt_bookNameKeyTyped

    private void txt_bookNameVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txt_bookNameVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookNameVetoableChange

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        AddBook addBook = new AddBook();
        addBook.setVisible(true);        
    }//GEN-LAST:event_jPanel23MouseClicked

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        
    }//GEN-LAST:event_productTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel book;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro productTable;
    private javax.swing.JTextField txt_bookName;
    // End of variables declaration//GEN-END:variables
}
